apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-zjpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-zjpe
    app.kubernetes.io/part-of: test-app-urub
  name: test-component-zjpe
  namespace: build-e2e-elge-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-zjpe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-zjpe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:d33f40690b044896bd57d61d4ac0b4be
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
